sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Lei.1692
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t7hBcVD5bXf4PFt49ee
    access-key-secret: kQfjuLNofgf4yYQxa7Z6iuHVtXZNVu
    bucket-name: lwf-sky-take-out
  redis:
    host: 175.24.201.135
    port: 6379
    password: 123456
    database: 5

